Support unix domain sockets (local addresses)
elixir-mint/mint pull request #283
Opened 2020-10-27 13:22 UTC by myobie

This PR adds support for unix domain sockets by accepting a special hostname prefixed with `unix://` to indicate it's an [`inet:local_address`](http://erlang.org/doc/man/inet.html#type-local_address).

_Aside: I believe Mint should eventually accept all types of addresses supported by [`gen_tcp:connect/3`](http://erlang.org/doc/man/gen_tcp.html#connect-3); however, that would be a much larger refactor which more-than-likely renames `hostname` to `address` and adds references the address types from `inet`._

Example usage could be:

```ex
{:ok, conn} = Mint.HTTP.connect(:http, "unix:///tmp/consul.sock", 0)
```

While I have tested this "live," I am unsure how to test this programmatically and would welcome any help getting that setup. I did notice [the PR which added ipv6 support](https://github.com/elixir-mint/mint/pull/270/files) didn't add additional tests so maybe it's alright to go without them?

2020-10-27 15:06 UTC, ericmj commented
Does cowboy support connecting over unix sockets? If so you can add a test the connects to a cowboy server.

Won't the `Host` header be incorrect unless the user manually sets it? Does `:ssl` support unix sockets?

2020-10-27 15:40 UTC, myobie commented
@ericmj good questions.

Yes it will be incorrect if it's not set by the user and that is expected. Not every server is going to validate the host header. `curl` has a advantage for this since one must specify a complete URL so it can take it out of that URL (both of the below approaches work):

```sh
curl --unix-socket /tmp/consul.sock http://localhost/v1/agent/members
# or
curl --unix-socket /tmp/consul.sock -H'Host: localhost' http://-/v1/agent/members
```

It seems [cowboy should support unix domain sockets](https://github.com/ninenines/cowboy/issues/803) so I will try writing a test case for that. About `:ssl`, I _assume_ it works no matter the type of socket but it is something a test case would help make for certain.

2020-10-27 16:46 UTC, ericmj commented
We have discussed options for passing an overriding address in this issue: https://github.com/elixir-mint/mint/pull/282#issuecomment-703535702. We could potentially pass the unix socket name the same way.

Another option is to do the refactor from hostname to address like you are suggesting. With that refactor we should also add a `:hostname` option that will be used for the `Host` header and for SSL hostname verification and SNI.

/cc @whatyouhide

2020-10-27 20:44 UTC, myobie commented
Note: `{:local, path}` doesn't seem to be valid for OTP <19: https://github.com/elixir-mint/mint/pull/283/checks?check_run_id=1317106396#step:6:601

2020-10-29 11:17 UTC, myobie commented
@ericmj I've pushed a test file which tests both transports (so `:gen_tcp` and `:ssl`) and they both work with unix sockets. I'll figure out how to tell the older OTP CI to skip the tests, but is there anything else you think is missing from this? Thanks 🙏

2020-10-29 12:28 UTC, ericmj commented
I don't think we should add a `:hostname` transport option that only the SSL transport uses and does not affect the `Host` header. We should wait until we get @whatyouhide's thoughts on https://github.com/elixir-mint/mint/pull/283#issuecomment-717376133.

2020-10-29 13:10 UTC, myobie commented
> I don't think we should add a `:hostname` transport option that only the SSL transport uses and does not affect the `Host` header. We should wait until we get @whatyouhide's thoughts on [#283 (comment)](https://github.com/elixir-mint/mint/pull/283#issuecomment-717376133).

OK, I was thinking the same thing. I wanted to first get a test to pass to show that `:ssl` does support the unix socket. I think having a `:hostname` option that could then be merged into `:transport_opts` so it could be used for both the `Host` header and for the ssl is very doable and I can get that working tomorrow or next week.

2020-11-02 08:37 UTC, whatyouhide commented
@ericmj I start to see the value in renaming all docs to have `address` in place of `hostname`, and adding a `hostname` option that sets the value of the `Host` header (with sensible defaults so that for 99% of use cases users don't have to set it).

2020-11-02 12:34 UTC, ericmj commented
Great, thanks for the feedback. So I think these are the steps we should do:

1. Rename `hostname` parameter to `address` and accept all address types the underlying transports accept.
2. Add a `:hostname` connection option. This option will be used for the `Host` header, and passed down as an option to the transports to use for hostname verification, SNI, etc.
3. The `:hostname` option is required if `address` is not a string, otherwise it defaults to the same value as `address`.

This should hopefully address (no pun intended) all concerns in this PR and in #282. WDYT?

2020-11-03 10:29 UTC, myobie commented
I've updated the top comment / description to include the steps you mentioned @ericmj. Thanks for being open to the change @whatyouhide.

2020-11-04 08:44 UTC, myobie commented
@ericmj I've pushed my first attempt at accepting all types of addresses along with a new `:hostname` option. I currently place a `:hostname` option into `transport_opts` every time, so it will either be the address or the `:hostname` option provided during connect. The `Host` header is being set like it was before, since I didn't modify the conn structs – we don't need the `address` anymore after `connect` makes a `socket`.

I also noticed the tests for OTP 18.3 + elixir 1.53 are failing because `erlex` now requires `>= 1.6`. Should we remove that version combo from the matrix or mark that test as optional?

2020-11-04 19:15 UTC, ericmj commented
> I also noticed the tests for OTP 18.3 + elixir 1.53 are failing because erlex now requires >= 1.6. Should we remove that version combo from the matrix or mark that test as optional?

I don’t see any tests failing because of erlex, I only see the new tests failing. Can you link to the failed test?

2020-11-04 20:03 UTC, ericmj reviewed
Looks great, I only have a few comments.

2020-11-04 20:03 UTC, ericmj commented on test/mint/unix_socket_test.exs
> +    unless is_unix?() && otp_19?() do
Let’s change this to a `@tag :skip` before the test.

2020-11-04 20:03 UTC, ericmj commented on test/support/mint/http1/test_server.ex
> +  def start do
Let’s revert this change.

2020-11-04 20:03 UTC, ericmj commented on test/support/mint/http1/test_server.ex
> +  def loop(listen_socket, parent, server_ref) do
Let’s revert this change.

2020-11-04 20:03 UTC, ericmj commented on test/mint/http1/conn_test.exs
> +  alias HTTP1.TestServer
Let’s revert this change.

2020-11-05 14:19 UTC, myobie commented
> > I also noticed the tests for OTP 18.3 + elixir 1.53 are failing because erlex now requires >= 1.6. Should we remove that version combo from the matrix or mark that test as optional?
> 
> I don’t see any tests failing because of erlex, I only see the new tests failing. Can you link to the failed test?

Gah, yes, you are right. I misunderstood this error https://github.com/elixir-mint/mint/pull/283/checks?check_run_id=1351815687#step:6:12

2020-11-05 14:26 UTC, myobie commented on lib/mint/core/transport/ssl.ex
> +    opts = Keyword.delete(opts, :hostname)
It does complain and we see a lot of test failures with `%Mint.TransportError{reason: {:options, {:socket_options, [hostname: "localhost", ...]}}}` in the output

2020-11-05 14:59 UTC, myobie commented on test/mint/unix_socket_test.exs
> +    unless is_unix?() && otp_19?() do
@ericmj OK, I've made a helper to conditionally tag it as `:skip` and I've added `:skip` to the list to be excluded by default.

2020-11-05 16:45 UTC, ericmj approved these changes
This looks really good. Just one final comment.

2020-11-05 16:45 UTC, ericmj commented on test/test_helper.exs
> +ExUnit.start(exclude: [:proxy, :skip])
This change is not necessary.

2020-11-05 17:00 UTC, whatyouhide requested changes

2020-11-05 18:58 UTC, ericmj commented on lib/mint/types.ex
> +  @type address :: :inet.socket_address() | :inet.hostname()
Good catch. Maybe we should replace `:inet.hostname()` with `String.t()`?

2020-11-05 21:44 UTC, myobie commented on lib/mint/types.ex
> +  @type address :: :inet.socket_address() | :inet.hostname()
[`:inet.socket_address()`](http://erlang.org/doc/man/inet.html#type-socket_address) allows `any` so it does allow `binary` technically, but I think it could be a good idea to replace these with a more explicit list of "desired types" instead of the list of "technically allowed types" by the underlying `connect` functions.

2020-11-05 21:53 UTC, myobie commented on lib/mint/types.ex
> +  @type address() :: :inet.socket_address() | :inet.hostname()
```suggestion
  @type address() :: :inet.socket_address() | String.t()
```

Related to https://github.com/elixir-mint/mint/pull/283#discussion_r518203488 

Also I misunderstood the erlang `any` to be the same as the elixir typespec `any` and I just realized it would actually be the atom `:any` so I was wrong with my most recent comment in the previous discussion 😓 sorry about that. I will say going back and forth from erlang to elixir every day the past couple weeks has been tough 😅 

/cc @whatyouhide and @ericmj

2020-11-12 07:56 UTC, whatyouhide approved these changes

2020-11-12 07:57 UTC, merged