Allow iolists as header values
elixir-mint/mint pull request #304
Opened 2021-03-27 23:57 UTC by dsdshcym

closes #272 

1. this PR is the silliest solution: calling `IO.iodata_to_binary/1` to convert all the header values to binary first
   1) to fully support iolist, we need to update HPACK module to encode/decode iolist as well, which requires some work (encoding then decoding will no longer be circular) & may still not get the performance boost (may need to convert iolist to binary anyway)
   2) based on my understanding, the main request of #272 is to add iolists support for convenience use, instead of for better performance
   3) so I think we can add this support first, then think of ways to optimize later
2. this PR adds 2 integration tests since I don't know the best place to unit test it. 
    Let me know if there is a better place to test this.

2021-03-28 01:24 UTC, dsdshcym commented on test/mint/http1/integration_test.exs
> +
an alternative would be to leverage httpbin.org/headers:


```elixir
    test "requests with iolist in header values" do
      headers = [{"iolist-header", ["io", '-', "list"]}]
      assert {:ok, conn} = HTTP1.connect(:http, "httpbin.org", 80)
      assert {:ok, conn, request} = HTTP1.request(conn, "GET", "/headers", headers, nil)
      assert {:ok, _conn, [_status, _headers | responses]} = receive_stream(conn)

      assert merge_body(responses, request) =~ ~s("Iolist-Header": "io-list")
    end
```

2021-03-28 14:51 UTC, ericmj reviewed
I don't think we should support iodata unless they have a performance benefit. WDYT @whatyouhide?

2021-03-28 14:51 UTC, ericmj commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
We need to separate the types for request and response headers since response headers will always be binary.

2021-03-28 14:51 UTC, ericmj commented on test/mint/http1/integration_test.exs
> +    test "requests with iolist in header values" do
I don't think this should be an integration test, you can add the test to https://github.com/elixir-mint/mint/blob/master/test/mint/http1/request_test.exs instead.

2021-03-28 14:51 UTC, ericmj commented on test/mint/http1/integration_test.exs
> +    test "requests with iolist in header values" do
Same for the HTTP/2 test.

2021-03-29 13:23 UTC, dsdshcym commented
> I don't think we should support iodata unless they have a performance benefit.

Okay, let me know your decisions. 
I'll update this PR according to the review comments if we decide to add it

2021-03-29 13:25 UTC, whatyouhide requested changes

2021-03-29 13:25 UTC, whatyouhide commented on lib/mint/http1/request.ex
> +    |> Enum.reduce("", fn {name, value}, acc ->
We don't need to loop through the list of headers twice. Please change this to:

```suggestion
    Enum.reduce(headers, "", fn {name, value}, acc ->
      value = IO.iodata_to_binary(value)
```

2021-03-29 13:25 UTC, whatyouhide commented on lib/mint/http2.ex
> +      |> convert_header_value_to_binary()
We shouldn't loop through headers twice. We can downcase header names and convert values to binaries in a single pass. Can you refactor this code so that it does that? Thanks!

2021-03-29 13:25 UTC, whatyouhide commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
This is a breaking type change. @ericmj how do you want to handle it? I’m ok with leaving `headers/0` as the response headers and introducing `request_headers() :: [{header_name :: String.t(), header_value :: iodata()}] | headers()` if we want to be clear and have the clear superset of type relation.

2021-03-29 13:44 UTC, dsdshcym commented on test/mint/http1/integration_test.exs
> +    test "requests with iolist in header values" do
We don't have a `HTTP2.Request` module so we can't add a unit test easily...
Do you want me to extract this module?
Probably with these functions:
- `encode_headers`
- `encode_trailing_headers`
- `encode_data`

This seems to be a large refactoring 🤔

2021-03-29 13:53 UTC, dsdshcym commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
Added `response_headers` in https://github.com/elixir-mint/mint/pull/304/commits/2c4e4d8268331169903ebb681e17ab11099d7edc

I think it would be better if we can change `headers` to `request_headers` for clarity

2021-03-29 14:09 UTC, dsdshcym commented on test/mint/http1/integration_test.exs
> +    test "requests with iolist in header values" do
Also, I can't add an unit test for encoding iolist in HTTP2 trailing headers due to the same reason

2021-03-29 14:10 UTC, dsdshcym commented on lib/mint/http2.ex
> +      |> convert_header_value_to_binary()
Updated in https://github.com/elixir-mint/mint/pull/304/commits/d8c1eade1056481cf2b430a23d744c370e3c411e

2021-04-02 16:24 UTC, wojtekmach commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
@whatyouhide I'm curious to learn more about your back'n'forth of whether this is a breaking change, hope that's ok :)

Say I have this function:

```elixir
  @spec decode(binary, Mint.Types.headers()) :: binary()
  def decode(body, headers) do
    case List.keyfind(headers, "content-type", 0) do
      {_, "application/json"} ->
        Jason.decode!(body)

      nil ->
        body
    end
  end
```

if `Mint.Types.headers()` is widened to support iodata but decode/2 above remains unchanged, calling it with `decode("42", [{"content-type", ["application/", "json"]}])` will give the wrong result. It is not a breaking change because `decode("42", [{"content-type", ["application/", "json"]}])` didn't work before so there's nothing to break? It is not a breaking change because response headers would never have been an iodata as it's always a binary coming from the socket?

Paraphrasing Rich Hickey (I believe you're familiar with these concepts): changing a function to accept _more_ is compatible (accepting _less_ isn't) and changing a function to return _less_ is compatible (and returning _more_ isn't). This presents an interesting problem for exporting types like Mint.Types.* does: we don't know how these types will be used! If someone uses the type for return value and the type is widened, does that count as an incompatibility?

2021-04-03 17:26 UTC, ericmj commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
> If someone uses the type for return value and the type is widened, does that count as an incompatibility?

Presumably this does not matter in practice because although the contract changed the functionality did not so you won't be returning the added types.

2021-04-03 17:27 UTC, ericmj commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
What's the reasoning for only `header_value` to be iodata. Either we support iodata fully or we don't support in my opinion.

2021-04-03 17:32 UTC, ericmj commented
While I think we should support iodata for performance I still don't think there's any point in supporting it in the API unless there are performance benefits. The API is cleaner and we have less complexity when we only support binaries, so adding iodata only has drawbacks as it is right now.

2021-04-07 10:06 UTC, wojtekmach commented on lib/mint/types.ex
> +  @type headers() :: [{header_name :: String.t(), header_value :: iodata()}]
Right, good point. I think the idea was: you look at the `decode/2` function above with its claimed inputs and you pass an input that it's supposed to support but it actually doesn't, _yet_. That is, you changed a caller upstream of decode/2 and expected things to work (they type check, hehe) but they don't. Not sure if something like this actually comes up or is sensible. But yeah, if what I'm saying makes sense this means that once you export a type you can never ever change it which seems too restrictive. Nevermind!

2021-04-07 11:15 UTC, ericmj commented
Closing this due to above stated reason. Thanks for the PR @dsdshcym.

2021-04-07 11:15 UTC, closed without merging

2021-04-12 03:38 UTC, dsdshcym commented
No problem, thanks for your time! @ericmj