Add test demonstrating use of connection socket
elixir-mint/mint pull request #310
Opened 2021-04-15 20:01 UTC by lukebakken

#309

cc @ericmj

2021-04-17 16:29 UTC, whatyouhide requested changes
Requested a couple of changes but looking good overall!

2021-04-17 16:29 UTC, whatyouhide commented on lib/mint/http.ex
> +  # Made public to be used with proxying and retrieving information from the socket.
We don't need this comment anymore.

```suggestion
```

2021-04-17 16:29 UTC, whatyouhide commented on lib/mint/http.ex
> +  Do not the returned socket to change its internal state. Only read information from the socket.
```suggestion
  Do not use the returned socket to change its internal state. Only read information from the socket.
```

2021-04-17 16:29 UTC, whatyouhide commented on lib/mint/core/transport/ssl.ex
> -  defp ssl_version() do
Let's not move this to utils because it belongs in the SSL module. Instead, make this public and call `Mint.Core.Transport.SSL.ssl_version()` in the test. Thanks!

2021-04-17 17:12 UTC, ericmj commented
The same change should be done to `Mint.HTTP1.get_socket/1` and `Mint.HTTP2.get_socket/1` as well.

2021-04-18 13:01 UTC, lukebakken commented
@ericmj @whatyouhide these changes will be released as version `1.3.0`, correct? Should I get [`CHANGELOG.md`](https://github.com/elixir-mint/mint/blob/master/CHANGELOG.md) entries for this PR here as well?

2021-04-19 07:16 UTC, whatyouhide commented
@lukebakken we're not sure when we will release changes, it depends on what other features are pending and a few other factors. Don't change the CHANGELOG, we'll take care of it when we cut a release, thanks! 💟

2021-04-19 07:18 UTC, whatyouhide commented on lib/mint/http2.ex
> +  """
```suggestion
  @doc """
  See `Mint.HTTP.get_socket/1`.
  """
```

2021-04-19 07:18 UTC, whatyouhide commented on lib/mint/http1.ex
> +  """
```suggestion
  @doc """
  See `Mint.HTTP.get_socket/1`.
  """
```

2021-04-19 07:19 UTC, whatyouhide approved these changes

2021-04-19 09:59 UTC, ericmj approved these changes
Thank you! 💜

2021-04-19 09:59 UTC, merged