add Mint.HTTP.module/1 to describe the conn module given a conn
elixir-mint/mint pull request #324
Opened 2021-07-21 19:16 UTC by andyleclair

@ericmj it seems like that could also be achieved by making `Mint.HTTP.conn_module` public, but I'm not sure about `UnsafeProxy`. Since it uses `Mint.HTTP1` under the hood should we return `Mint.HTTP1?` `UnsafeProxy`? I don't really know what `UnsafeProxy` gets used for, guessing non-https proxying

2021-07-22 07:58 UTC, whatyouhide commented
Would it be better to expose the _protocol_ instead of the module? Something like `get_protocol(Mint.HTTP.t()) :: :"http1.1" | :http2`?

2021-07-22 08:01 UTC, whatyouhide commented
I see that @ericmj suggested the module-based solution in https://github.com/elixir-mint/mint/issues/263. Any reason not to go with the protocol instead?

2021-07-22 09:50 UTC, ericmj commented
In the scenario from #263 I think it's better to return the connection module since they want to check if they can call functions on a specific module.

There may be a use case to get the protocol as well but that would need a different API I think since we support HTTP 0.9, 1.0, 1.1, and 2.0. Maybe `protocol_version(t()) :: {pos_integer(), pos_integer()}`?

2021-07-22 12:18 UTC, whatyouhide commented
@ericmj yes I like the protocol + version tuple. Can't folks map the protocol to the HTTP module? Wondering if we should keep the module internal, that's all :)

2021-07-22 12:24 UTC, ericmj commented
I don't think we need to keep it internal, `Mint.HTTP1` and `Mint.HTTP2` are public documented modules.

We can add `protocol(t()) :: {atom(), pos_integer(), pos_integer()}` instead but then we also need to document that you can call `Mint.HTTP1` functions with a connection struct returned from `Mint.HTTP.connect()` if `Mint.HTTP.protocol()` returns `{:http, 0 | 1, _}`. It feels more complicated when we can instead return the module directly.
?

2021-07-23 10:17 UTC, whatyouhide commented
I’m worried about the proxy too here. If we return the module it's not guaranteed that you can call functions on that, is it? Because it could be a proxy conn>

2021-07-23 14:26 UTC, andyleclair commented
For our purposes, we're looking to differentiate in order to fix a bug with `transfer-encoding: chunked` (see also: https://github.com/appcues/mojito/pull/87). We don't need to call functions on the module, the module name was good enough

2021-07-23 15:23 UTC, ericmj commented
> Because it could be a proxy conn?

Yeah, this would break on a proxy conn.

@andyleclair Sorry for the back and forth, but could you add a `protocol(t()) :: {atom(), pos_integer(), pos_integer()}` function instead?

2021-07-23 15:29 UTC, andyleclair commented
hey no problem! I'm glad to help. thank you both for your time (and for considering this PR)

2021-07-23 17:02 UTC, andyleclair commented
From my understanding, I'd need a request to determine the full protocol from the conn, right? Obviously for HTTP2, it's just `{:http, 2, 0}` but to tell `0.9` from `1.0` from `1.1` we'd need a request body as the version is returned from the server

2021-07-27 13:20 UTC, ericmj commented
> From my understanding, I'd need a request to determine the full protocol from the conn, right? Obviously for HTTP2, it's just {:http, 2, 0} but to tell 0.9 from 1.0 from 1.1 we'd need a request body as the version is returned from the server

Ugh, good point.

In that case I am leaning towards returning `:http1 | :http2`. Alternatively return the module names, but add support for `%UnsafeProxy{}` in `Mint.HTTP1` to handle that case. But I want to hear what @whatyouhide thinks.

2021-07-28 18:53 UTC, andyleclair commented
Under the hood `UnsafeProxy` is using `Mint.HTTP1` but that strikes me as leaking an implementation detail. I don't have enough context on what `UnsafeProxy` is for or does, but from reading the code, it seems like `Mint.HTTP1` but with some connection proxy details

2021-08-23 06:40 UTC, whatyouhide commented
I would just go with `:http1`/`:http2`. We can call the function `major_protocol` or something like this so that we keep `protocol/1` open for the future. Or even better, we have `protocol(Conn.t()) :: :http1 | :http2` and in the future we can add `protocol(Conn.t(), :with_minor_version) :: {...}` if the need arises.

2021-09-01 18:25 UTC, ericmj commented
Looks good but I think we should handle UnsafeProxy or did we decide not to?

2021-09-01 18:25 UTC, ericmj approved these changes

2021-09-01 18:27 UTC, andyleclair commented
@ericmj since `Mint.HTTP.t()` is defined as `Mint.HTTP1.t() | Mint.HTTP2.t()` I decided against it, but I can add it.

2021-09-02 05:01 UTC, whatyouhide requested changes
Left a few suggestions, plus I’m requesting changes because we need to add tests for this 🙃

2021-09-02 05:01 UTC, whatyouhide commented on lib/mint/http.ex
> +  def protocol(%Mint.HTTP2{}), do: :http2
I think we need to add a clause for `Mint.UnsafeProxy` conns:

```suggestion
  def protocol(%Mint.HTTP2{}), do: :http2
  def protocol(%Mint.UnsafeProxy{state: internal_conn}), do: protocol(internal_conn()
```

right @ericmj?

2021-09-02 15:39 UTC, andyleclair commented on lib/mint/http.ex
> +      :http1 = Mint.HTTP.protocol(conn)
I added doctests, is that ok?

2021-09-02 15:42 UTC, andyleclair commented
@whatyouhide it looks like using `since: "1.4.0"` breaks on older elixir/erlang versions

2021-09-03 06:45 UTC, whatyouhide commented
@andyleclair you can do `@doc since` conditionally, something like this:

```elixir
if Version.compare(System.version(), "<whatever version introduced @doc since>") in [:eq, :gt] do
  @doc since: "1.4.0"
end
```

2021-09-10 18:06 UTC, whatyouhide approved these changes

2021-09-12 14:13 UTC, merged