Add proxy_headers field to HTTP structs and fill this field in tunnel proxy
elixir-mint/mint pull request #329
Opened 2021-09-06 19:59 UTC by exit9

When connecting over HTTPS the only way to talk with proxy server is sending and receiving headers on connect method.

2021-09-07 17:45 UTC, ericmj commented
A function to access the proxy headers is also needed since the struct fields are private API.

2021-09-08 06:01 UTC, whatyouhide requested changes
Left a couple comments, but we also need tests for this before we'll be able to merge it in 🙃 Thanks @exit9! 💟

2021-09-08 06:01 UTC, whatyouhide commented on lib/mint/tunnel_proxy.ex
> +      {:ok, conn} -> {:ok, struct(conn, proxy_headers: proxy_headers)}
```suggestion
      {:ok, conn} -> {:ok, struct!(conn, proxy_headers: proxy_headers)}
```

2021-09-08 06:01 UTC, whatyouhide commented on lib/mint/tunnel_proxy.ex
> +      {:ok, struct(conn, proxy_headers: proxy_headers)}
```suggestion
      {:ok, struct!(conn, proxy_headers: proxy_headers)}
```

2021-09-08 06:01 UTC, whatyouhide commented on lib/mint/http2.ex
> +    proxy_headers: []
Looks like we would never use this, right? Why are we adding this to the HTTP/2 conn?

2021-09-09 11:03 UTC, exit9 commented on lib/mint/tunnel_proxy.ex
> +      {:ok, conn} -> {:ok, struct(conn, proxy_headers: proxy_headers)}
fixed

2021-09-09 11:08 UTC, exit9 commented on lib/mint/http2.ex
> +    proxy_headers: []
I think here https://github.com/elixir-mint/mint/blob/0fdf1e01af21ead6957f015dd8b33280f574b08c/lib/mint/tunnel_proxy.ex#L42 we can switch to HTTP2 conn and should store headers in HTTP2 too.

2021-09-09 13:21 UTC, ericmj commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(%__MODULE__{proxy_headers: proxy_headers}), do: proxy_headers
This should never be called since you cannot use both a tunnel and an unsafe proxy for the same connection.

2021-09-09 13:32 UTC, exit9 commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(%__MODULE__{proxy_headers: proxy_headers}), do: proxy_headers
Yes, you can't. But unsafe proxy also have proxy_headers field so I decided to add this function for full implementation of the behaviour and access to this field. Shouldn't I?

2021-09-09 13:58 UTC, ericmj commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(%__MODULE__{proxy_headers: proxy_headers}), do: proxy_headers
The `:proxy_headers` in this struct are for requests, not what the proxy responds with. Thinking more about it, this function should always return `[]`, since that's what non-tunnelled `Mint.HTTP1` and `Mint.HTTP2` will do.

2021-09-09 17:53 UTC, exit9 commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(%__MODULE__{proxy_headers: proxy_headers}), do: proxy_headers
fixed

2021-09-09 17:58 UTC, ericmj approved these changes

2021-09-09 17:58 UTC, ericmj commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(_), do: []
```suggestion
  def get_proxy_headers(%__MODULE__{}), do: []
```

For extra paranoia :)

2021-09-09 18:00 UTC, exit9 commented on lib/mint/unsafe_proxy.ex
> +  def get_proxy_headers(_), do: []
fixed))

2021-09-10 09:12 UTC, whatyouhide approved these changes

2021-09-10 09:12 UTC, whatyouhide commented on lib/mint/http.ex
> +  When using tunnel proxy and https there is the only way to exchange data with the proxy is through headers in the `CONNECT` method.
```suggestion
  When using tunnel proxy and HTTPs, the only way to exchange data with
  the proxy is through headers in the `CONNECT` method.
```

2021-09-10 09:12 UTC, whatyouhide commented on lib/mint/unsafe_proxy.ex
> +  """
```suggestion
  # The `%__MODULE__{proxy_headers: value}` here is the request headers,
  # not the proxy response ones. Unsafe proxy mixes its headers (if any)
  # with the regular response headers, so you can get them there.
```

2021-09-10 09:14 UTC, merged