Contributing and testing housekeeping
elixir-mint/mint pull request #440
Opened 2024-06-30 15:21 UTC by kianmeng

List of changes:
- autolink Apache license and switch to https
- bump Alpine Linux image from 3.17.2 to 3.20.1
- exclude :integration test by default
- fix cannot build Docker images with Podman Compose
- fix incorrect CI badge which still point to Travis CI
- fix markups in readme by `prettier`
- replace :requires_internet_connection with :integration tag for consistentcy
- tag integration test module in http1 with :integration
- update console commands markdown so we can click and copy them

2024-06-30 15:22 UTC, kianmeng commented on docker-compose.yml
> +    image: docker.io/caddy:2.6.4-alpine
Issue when using `podman-compose`:

```
Error: short-name "caddy:2.6.4-alpine" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

2024-06-30 15:23 UTC, kianmeng commented on test/docker/tinyproxy-auth/Dockerfile
> +FROM alpine:3.20.1
I can't seemed to get Apline Docker image 3.17.2 to work:

```sh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz                                                             
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/main: temporary error (try again later)                                     
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz                                                        
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.17/community: temporary error (try again later)
ERROR: unable to select packages:                                    
  tinyproxy (no such package): 
    required by: world[tinyproxy]
```

2024-06-30 15:24 UTC, kianmeng commented on test/mint/http2/integration_test.exs
> +  @moduletag :integration
Using shorter `:integration` tag to follow the short name convention of `:proxy`. Also, I kept typing `require_internet_connection` without the `s`.

2024-06-30 15:25 UTC, kianmeng commented on test/test_helper.exs
> +ExUnit.start(exclude: [:integration, :proxy])
Exclude the `:integration` and `:proxy` tagged tests by default, as it should work by default when running `mix test`.

2024-06-30 15:25 UTC, kianmeng commented on README.md
> +> https://www.apache.org/licenses/LICENSE-2.0
Markdown will generate this as hyperlink by indenting a URL link.

2024-07-01 08:05 UTC, whatyouhide requested changes
This is a lot of different changes 🙃 In general, I'd recommend to split these out in multiple PRs next time so that we can pick and choose. I left a few blocking comments about stuff that I would prefer not to change. Thanks for the contribution!

2024-07-01 08:05 UTC, whatyouhide commented on README.md
> +Mint is different from most Erlang and Elixir HTTP clients because it provides a _process-less architecture_. Instead, Mint is based on a functional and immutable data structure that represents an HT
Nope, let's leave the `*` please (here and in all the README) 🙃 Thank you.

2024-07-01 08:05 UTC, whatyouhide commented on README.md
> +You may obtain a copy of the License at
There's no need to de-indent this, thanks!

2024-07-01 08:05 UTC, whatyouhide commented on test/mint/http2/integration_test.exs
> +  @moduletag :integration
I much prefer the explicit `requires_internet_connection`. Can we revert this change please?

2024-07-01 08:05 UTC, whatyouhide commented on .github/workflows/main.yml
> +        run: mix test --trace --include integration --include proxy
Let's leave the tag on by default please. I'd much rather contributors see failing test when they run `mix test` and have to start some containers, rather than seeing everything green when there could be issues. Thanks.

2024-07-01 09:54 UTC, kianmeng commented
> This is a lot of different changes 🙃 In general, I'd recommend to split these out in multiple PRs next time so that we can pick and choose. I left a few blocking comments about stuff that I would prefer not to change. Thanks for the contribution!

I will close this PR and submit smaller PRs instead with the changes you intend to keep. It's more easier that way.

2024-07-01 09:54 UTC, closed without merging